pre_roles:
  - system # fix later, passwordless sudo not working
  - 1password
  - ssh
  - fonts
  - oh-my-posh
  - starship
  - tmux
  - zoxide
  - bash
  - zsh
  - jdk

default_roles:
  - appcleaner
  - balenaetcher
  - bat
  - brave
  - brew-cask-completion
  - btop
  - cloc
  - colordiff
  - coreutils
  - direnv
  - discord
  - docker
  - dosbox
  - ffmpeg
  - flatpak
  - flux
  - fzf
  - gcloud
  - git
  - gnu-sed
  - gnupg
  - go
  - handbrake
  # - helm # fix later
  - helmfile
  - htop
  - httpie
  - insomnia
  - jdownloader
  - jetbrains-toolbox
  - jj
  - jq
  - k8s
  - k9s
  - kitty
  - kotlin
  - lazygit
  - libreoffice
  - locationsimulator
  - lua
  - lunar
  - m-cli
  - mailsy
  - mas
  - maven
  - mdv
  - microsoft-remote-desktop
  - moonlight
  - mpv
  - neofetch
  - neovim
  - nmap
  - nordvpn
  - notion
  - npm
  - nvm
  - obs
  - obsidian
  - onyx
  - opentofu
  - openvpn-connect
  - openwebstart
  - operator-sdk
  - podman
  - postman
  - pulumi
  - pwsh
  - python
  - quicklook
  - ranger
  - rawtherapee
  - raycast
  - shellcheck
  - signal
  - slack
  - spectacle
  - speedtest
  - spring-boot
  - steam
  - system
  - talosctl
  - terminal-notifier
  - the-unarchiver
  - thefuck
  - tmux
  - tor-browser
  - trash
  - tree
  - utm
  - vlc
  - vscode
  - watch
  - wget
  - wireshark
  - xquartz
  - yarn
  - ykman
  - yq
  - yt-dlp

op:
  k8s:
    kubeconfig:
      account: "my.1password.com"
      uri: "op://Private/kubeconfig/notesPlain"

ssh:
  config:
    opLookup:
      account: "my.1password.com"
      uri: "op://Private/ssh-config/notesPlain"

gcloud:
  components:
    - "gke-gcloud-auth-plugin"
    - "kpt"
    - "config-connector"
    - "terraform-tools"
    - "docker-credential-gcr"

k8s:
  gke_clusters:
    - cluster_name: "gke-vs-stable"
      location: "europe-west3"
      project_id: "vs-stable"
    - cluster_name: "vs-config-controller"
      location: "europe-west4"
      project_id: "vs-config-controller"
    - cluster_name: "gke-vs-cops-sandbox"
      location: "europe-west3"
      project_id: "vs-cops-sandbox"
