# Base roles organized by category
base_roles:
  core:
    - system # fix later, passwordless sudo not working
    - 1password
    - ssh
    - fonts
    - gnupg
  shell:
    - bash
    - zsh
    - oh-my-posh
    - starship
    - tmux
    - kitty
    - neofetch
  cli:
    - zoxide
    - bat
    - btop
    - cloc
    - colordiff
    - coreutils
    - direnv
    - fzf
    - git
    - gnu-sed
    - htop
    - httpie
    - jj
    - jq
    - lazygit
    - mdv
    - nmap
    - ranger
    - shellcheck
    - speedtest
    - terminal-notifier
    - thefuck
    - trash
    - tree
    - watch
    - wget
    - yq
  dev:
    - jdk
    - go
    - kotlin
    - locationsimulator
    - lua
    - maven
    - neovim
    - npm
    - nvm
    - openwebstart
    - pwsh
    - python
    - utm
    - yarn
  devops:
    - argocd
    - docker
    - flux
    - gcloud
    # - helm # fix later
    - helmfile
    - k8s
    - k9s
    - opentofu
    - operator-sdk
    - podman
    - pulumi
    - talosctl
    - wireshark
  utils:
    - appcleaner
    - balenaetcher
    - brew-cask-completion
    - flatpak
    - jdownloader
    - lunar
    - m-cli
    - mailsy
    - mas
    - nordvpn
    - onyx
    - openvpn-connect
    - the-unarchiver
    - xquartz
    - ykman
  apps:
    - brave
    - discord
    - insomnia
    - jetbrains-toolbox
    - libreoffice
    - microsoft-remote-desktop
    - notion
    - obsidian
    - postman
    - raycast
    - signal
    - slack
    - tor-browser
    - vscode
  media:
    - ffmpeg
    - handbrake
    - mpv
    - obs
    - quicklook
    - rawtherapee
    - vlc
    - yt-dlp
  gaming:
    - dosbox
    - moonlight
    - steam

# Override controls
exclude_roles: []
exclude_categories: []

op:
  - id: "kubeconfig"
    account: "my.1password.com"
    uri: "op://Private/kubeconfig/notesPlain"
  - id: "ssh-config"
    account: "my.1password.com"
    uri: "op://Private/ssh-config/notesPlain"
  - id: "git-user-personal"
    account: "my.1password.com"
    uri: "op://Private/Github/git_username"
  - id: "git-email-personal"
    account: "my.1password.com"
    uri: "op://Private/Github/username"
  - id: "git-signingkey-personal"
    account: "my.1password.com"
    uri: "op://Private/SSH-Sign/public key"
  - id: "git-user-work"
    account: "my.1password.com"
    uri: "op://Private/Okta/git_username"
  - id: "git-email-work"
    account: "my.1password.com"
    uri: "op://Private/Okta/username"
  - id: "git-signingkey-work"
    account: "viesure.1password.com"
    uri: "op://Employee/SSH-Sign/public key"

ssh:
  config:
    opLookupId: ssh-config

gcloud:
  components:
    - "gke-gcloud-auth-plugin"
    - "kpt"
    - "config-connector"
    - "terraform-tools"
    - "docker-credential-gcr"

k8s:
  kubeconfig:
    opLookupId: kubeconfig
  gke_clusters:
    - cluster_name: "gke-vs-stable"
      location: "europe-west3"
      project_id: "vs-stable"
    - cluster_name: "vs-config-controller"
      location: "europe-west4"
      project_id: "vs-config-controller"
    - cluster_name: "gke-vs-cops-sandbox"
      location: "europe-west3"
      project_id: "vs-cops-sandbox"
