pre_roles:
  - core/system # fix later, passwordless sudo not working
  - core/1password
  - core/ssh
  - core/fonts
  - shell/oh-my-posh
  - shell/starship
  - shell/tmux
  - cli/zoxide
  - shell/bash
  - shell/zsh
  - dev/jdk

default_roles:
  - utils/appcleaner
  - utils/balenaetcher
  - cli/bat
  - apps/brave
  - utils/brew-cask-completion
  - cli/btop
  - cli/cloc
  - cli/colordiff
  - cli/coreutils
  - cli/direnv
  - apps/discord
  - devops/docker
  - gaming/dosbox
  - media/ffmpeg
  - utils/flatpak
  - devops/flux
  - cli/fzf
  - devops/gcloud
  - cli/git
  - cli/gnu-sed
  - core/gnupg
  - dev/go
  - media/handbrake
  # - devops/helm # fix later
  - devops/helmfile
  - cli/htop
  - cli/httpie
  - apps/insomnia
  - utils/jdownloader
  - apps/jetbrains-toolbox
  - cli/jj
  - cli/jq
  - devops/k8s
  - devops/k9s
  - shell/kitty
  - dev/kotlin
  - cli/lazygit
  - apps/libreoffice
  - dev/locationsimulator
  - dev/lua
  - utils/lunar
  - utils/m-cli
  - utils/mailsy
  - utils/mas
  - dev/maven
  - cli/mdv
  - apps/microsoft-remote-desktop
  - gaming/moonlight
  - media/mpv
  - shell/neofetch
  - dev/neovim
  - cli/nmap
  - utils/nordvpn
  - apps/notion
  - dev/npm
  - dev/nvm
  - media/obs
  - apps/obsidian
  - utils/onyx
  - devops/opentofu
  - utils/openvpn-connect
  - dev/openwebstart
  - devops/operator-sdk
  - devops/podman
  - apps/postman
  - devops/pulumi
  - dev/pwsh
  - dev/python
  - media/quicklook
  - cli/ranger
  - media/rawtherapee
  - apps/raycast
  - cli/shellcheck
  - apps/signal
  - apps/slack
  - cli/speedtest
  - dev/spring-boot
  - gaming/steam
  - core/system
  - devops/talosctl
  - cli/terminal-notifier
  - utils/the-unarchiver
  - cli/thefuck
  - shell/tmux
  - apps/tor-browser
  - cli/trash
  - cli/tree
  - dev/utm
  - media/vlc
  - apps/vscode
  - cli/watch
  - cli/wget
  - devops/wireshark
  - utils/xquartz
  - dev/yarn
  - utils/ykman
  - cli/yq
  - media/yt-dlp

op:
  k8s:
    kubeconfig:
      account: "my.1password.com"
      uri: "op://Private/kubeconfig/notesPlain"

ssh:
  config:
    opLookup:
      account: "my.1password.com"
      uri: "op://Private/ssh-config/notesPlain"

gcloud:
  components:
    - "gke-gcloud-auth-plugin"
    - "kpt"
    - "config-connector"
    - "terraform-tools"
    - "docker-credential-gcr"

k8s:
  gke_clusters:
    - cluster_name: "gke-vs-stable"
      location: "europe-west3"
      project_id: "vs-stable"
    - cluster_name: "vs-config-controller"
      location: "europe-west4"
      project_id: "vs-config-controller"
    - cluster_name: "gke-vs-cops-sandbox"
      location: "europe-west3"
      project_id: "vs-cops-sandbox"
