pre_roles:
  - system
  - 1password
  - ssh
  - fonts
  - oh-my-posh
  - starship
  - tmux
  - zoxide
  - bash
  - zsh

default_roles:
  - bat
  - brave
  - btop
  - discord
  - docker
  - flatpak
  - fzf
  # - gcloud
  - git
  - go
  # - helm # fix later
  # - jj
  - k8s
  - k9s
  - kitty
  - lazygit
  - lua
  - neofetch
  - neovim
  - npm
  - nvm
  - podman
  - pwsh
  - python
  - raycast

op:
  k8s:
    kubeconfig: "op://Private/kubeconfig/notesPlain"

ssh:
  config:
    opLookup:
      account: "my.1password.com"
      uri: "op://Private/ssh-config/notesPlain"

k8s:
  gke_clusters:
    - cluster_name: "gke-vs-stable"
      location: "europe-west3"
      project_id: "vs-stable"
    - cluster_name: "gke-vs-config-controller"
      location: "europe-west3"
      project_id: "vs-config-controller"
    - cluster_name: "gke-vs-cops-sandbox"
      location: "europe-west3"
      project_id: "vs-cops-sandbox"
