default_roles:
  - system
  - 1password
  - bash
  - bat
  - btop
  - discord
  - docker
  - flatpak
  - fonts
  - fzf
  - gcloud
  - git
  - go
  - helm
  - k8s
  - k9s
  - kitty
  - lazygit
  - lua
  - neofetch
  - neovim
  - npm
  - nvm
  - oh-my-posh
  - podman
  - pwsh
  - python
  - raycast
  - ssh
  - starship
  - tmux
  - zoxide
  - zsh

op:
  k8s:
    kubeconfig: "op://Private/k8s-config/kubeconfig"

k8s:
  gke_clusters:
    - cluster_name: "gke-vs-stable"
      location: "europe-west3"
      project_id: "vs-stable"
    - cluster_name: "gke-vs-config-controller"
      location: "europe-west3"
      project_id: "vs-config-controller"
    - cluster_name: "gke-vs-cops-sandbox"
      location: "europe-west3"
      project_id: "vs-cops-sandbox"

gcloud:
  components:
    - gsutil
    - bq
    - docker-credential-gcr
    - log-streaming
    - config-connector
    - gke-cloud-auth-plugin
