default_roles:
  - system
  - 1password
  - bash
  - bat
  - btop
  # - discord
  # - docker
  - flatpak
  - fonts
  - fzf
  # - gh
  - git
  - go
  - helm
  # - k8s
  - k9s
  - kitty
  - lazygit
  - lsd
  - lua
  - ncdu
  - neofetch
  - neovim
  - nerdfetch
  - npm
  - nvm
  - podman
  - pwsh
  - python
  - raycast
  # - ruby
  # - rust
  - slides
  - ssh
  - sshfs
  - starship
  - terraform
  - tmux
  - zoxide
  - zsh

k8s:
  repo:
    version: "v1.26"

helm:
  repos:
    - name: traefik
      url: https://helm.traefik.io/traefik

go:
  packages:
    - package: github.com/go-task/task/v3/cmd/task@latest
      cmd: task
    - package: github.com/gcla/termshark/v2/cmd/termshark@v2.4.0
      cmd: termshark
    # - package: github.com/stillmatic/chat@latest
    #   cmd: chat
