default_roles:
  - system
  - 1password
  - bash
  - bat
  - btop
  # - discord
  # - docker
  - flatpak
  - fonts
  - fzf
  # - gh
  - git
  - go
  - helm
  # - k8s
  - k9s
  - kitty
  - lazygit
  - lsd
  - lua
  - ncdu
  - neofetch
  - neovim
  - nerdfetch
  - npm
  - nvm
  - podman
  - pwsh
  - python
  - raycast
  # - ruby
  # - rust
  - slides
  - ssh
  - sshfs
  - starship
  - terraform
  - tmux
  - zoxide
  - zsh

op:
  k8s:
    kubeconfig: "op://Private/k8s-config/kubeconfig"

k8s:
  gke_clusters:
    - cluster_name: "gke-vs-stable"
      location: "europe-west3"
      project_id: "vs-stable"
    - cluster_name: "gke-vs-config-controller"
      location: "europe-west3"
      project_id: "vs-config-controller"
    - cluster_name: "gke-vs-cops-sandbox"
      location: "europe-west3"
      project_id: "vs-cops-sandbox"
