# Base roles organized by category
base_roles:
  core:
    - system # fix later, passwordless sudo not working
    - 1password
    - ssh
    - fonts
    - gnupg
    - mas
    - onedrive
  shell:
    - bash
    - zsh
    - oh-my-posh
    - starship
    - tmux
    - kitty
    - neofetch
  cli:
    - zoxide
    - bat
    - btop
    - cloc
    - colordiff
    - coreutils
    - direnv
    - fzf
    - git
    - gnu-sed
    - htop
    - httpie
    - jj
    - jq
    - lazygit
    - mdv
    - nmap
    - ranger
    - shellcheck
    - terminal-notifier
    - thefuck
    - trash
    - tree
    - watch
    - wget
    - yq
  dev:
    - jdk
    - go
    - jetbrains-toolbox
    - kotlin
    - locationsimulator
    - lua
    - maven
    # - neovim
    - npm
    - nvm
    - python
    - vim
    - vscode
    - xcode
    - yarn
  devops:
    - argocd
    - docker
    - flux
    - gcloud
    - helm
    - helmfile
    - k8s
    - k9s
    - opentofu
    - operator-sdk
    - podman
  utils:
    - appcleaner
    - balenaetcher
    - brew-cask-completion
    - dell-display-peripheral-manager
    - flatpak
    - hex-fiend
    - hp
    - insomnia
    - lunar
    - m-cli
    - mailsy
    - nordvpn
    - onyx
    - openvpn-connect
    - postman
    - speedtest
    - tailscale
    - the-unarchiver
    - windows-app
    - xquartz
    - ykman
  apps:
    - brave
    - libreoffice
    - notion
    - obsidian
    - raycast
    - signal
    - slack
    - safari-extensions
    - telegram
    - todoist
    - home-assistant
    - microsoft-to-do
  media:
    - ffmpeg
    - handbrake
    - mpv
    - obs
    - quicklook
    - vlc
  gaming:
    - moonlight

# Override controls
exclude_roles: []
exclude_categories: []

op:
  - id: "kubeconfig"
    account: "my.1password.com"
    uri: "op://Private/kubeconfig/notesPlain"
  - id: "ssh-config"
    account: "my.1password.com"
    uri: "op://Private/ssh-config/notesPlain"
  - id: "git-user-personal"
    account: "my.1password.com"
    uri: "op://Private/Github/git_username"
  - id: "git-email-personal"
    account: "my.1password.com"
    uri: "op://Private/Github/username"
  - id: "git-signingkey-personal"
    account: "my.1password.com"
    uri: "op://Private/SSH-Sign/public key"
  - id: "git-user-work"
    account: "my.1password.com"
    uri: "op://Private/Okta/git_username"
  - id: "git-email-work"
    account: "my.1password.com"
    uri: "op://Private/Okta/username"
  - id: "git-signingkey-work"
    account: "viesure.1password.com"
    uri: "op://Employee/SSH-Sign/public key"

ssh:
  config:
    opLookupId: ssh-config

gcloud:
  components:
    - "gke-gcloud-auth-plugin"
    - "kpt"
    - "config-connector"
    - "terraform-tools"
    - "docker-credential-gcr"

k8s:
  kubeconfig:
    opLookupId: kubeconfig
  gke_clusters:
    - cluster_name: "gke-vs-stable"
      location: "europe-west3"
      project_id: "vs-stable"
    - cluster_name: "vs-config-controller"
      location: "europe-west4"
      project_id: "vs-config-controller"
    - cluster_name: "gke-vs-cops-sandbox"
      location: "europe-west3"
      project_id: "vs-cops-sandbox"
