default_roles:
  - system
  - 1password
  - bash
  - bat
  - btop
  # - discord
  # - docker
  - flatpak
  - fonts
  - fzf
  # - gh
  - git
  - go
  - helm
  # - k8s
  - k9s
  - kitty
  - lazygit
  - lsd
  - lua
  - ncdu
  - neofetch
  - neovim
  - nerdfetch
  - npm
  - nvm
  - podman
  - pwsh
  - python
  - raycast
  # - ruby
  # - rust
  - slides
  - ssh
  - sshfs
  - starship
  - terraform
  - tmux
  - zoxide
  - zsh

