# Additional roles for personal environment organized by category
# Only add roles that are NOT already present in all.yaml
additional_roles: {}
  # Example: Add personal-specific roles per category as needed
  # core:
  #   - personal-security-tool
  # dev:
  #   - personal-dev-tool
  # utils:
  #   - personal-utility
  # apps:
  #   - personal-app

git:
  user:
    default:
      name:
        opLookupId: git-user-personal
      email:
        opLookupId: git-email-personal
      signingkey:
        opLookupId: git-signingkey-personal

    additional:
      - id: "work"
        name:
          opLookupId: git-user-work
        email:
          opLookupId: git-email-work
        signingkey:
          opLookupId: git-signingkey-work
        gitdir: "~/vs-workspace/"