# Additional roles for personal environment organized by category
# Only add roles that are NOT already present in all.yaml
additional_roles: {}
  # Example: Add personal-specific roles per category as needed
  # core:
  #   - personal-security-tool
  # dev:
  #   - personal-dev-tool
  # utils:
  #   - personal-utility
  # apps:
  #   - personal-app

git:
  user:
    default:
      name:
        opLookup:
          account: "my.1password.com" # Personal account
          uri: "op://Private/Github/git_username"
      email:
        opLookup:
          account: "my.1password.com" # Personal account
          uri: "op://Private/Github/username"
      signingkey:
        opLookup:
          account: "my.1password.com" # Personal account
          uri: "op://Private/SSH-Sign/public key"

    additional:
      - id: "work"
        name:
          opLookup:
            account: "my.1password.com" # Company account
            uri: "op://Private/Okta/git_username"
        email:
          opLookup:
            account: "my.1password.com" # Company account
            uri: "op://Private/Okta/username"
        signingkey:
          opLookup:
            account: "viesure.1password.com" # Company account
            uri: "op://Employee/SSH-Sign/public key"
        gitdir: "~/vs-workspace/"