---
- name: "{{ role_name }} | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yaml"
  register: distribution_config

- name: "{{ role_name }} | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yaml"
  when: distribution_config.stat.exists

- name: "{{ role_name }} | Create .ssh directory"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.ssh"
    state: directory
    mode: '0700'

- name: "{{ role_name }} | Create SSH config file from 1Password content"
  when: ssh.config.opLookupId is defined and op_lookup[ssh.config.opLookupId] is defined
  ansible.builtin.copy:
    content: "{{ op_lookup[ssh.config.opLookupId] }}"
    dest: "{{ ansible_user_dir }}/.ssh/config"
    mode: '0600'

# Note: FIDO key extraction has been moved to bin/dotfiles script
