---
- name: "K9s | MacOSX | Install k9s"
  community.general.homebrew:
    name: k9s
    state: present

#- name: "K9s | Ensure config directory exists"
#  ansible.builtin.file:
#    path: "{{ ansible_user_dir }}/Library/Application Support/k9s"
#    state: directory
#    mode: "0755"

#- name: "K9s | Copy config"
#  ansible.builtin.copy:
#    dest: "{{ ansible_user_dir }}/Library/Application Support/k9s/{{ item }}"
#    src: "{{ item }}"
#    mode: "0644"
#  loop:
#    - config.yaml
#    - aliases.yaml
