---
- name: "K9s | MacOSX | Install k9s"
  community.general.homebrew:
    name: k9s
    state: present

- name: "K9s | Copy config"
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/Library/Application Support/k9s/{{ item }}"
    src: "{{ item }}"
    mode: "0644"
  loop:
    - config.yaml
    - plugins.yaml
    - aliases.yaml

- name: "K9s | Copy skin config"
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/Library/Application Support/k9s/skins/{{ item }}"
    src: "{{ item }}"
    mode: "0644"
  loop:
    - catppuccin_mocha.yaml
