---
- name: "Bash | Get private variables from Vault"
  ansible.builtin.command: "op read '{{ secret.vault_path }}'"
  register: op_secret
  changed_when: false
  no_log: true

- name: "Bash | Set bash_private"
  ansible.builtin.set_fact:
    bash_private: "{{ bash_private | combine({ item.key: item.value }) }}"
  no_log: true
  with_items:
    - key: "{{ secret.name }}"
      value: "{{ op_secret.stdout }}"
