---
- name: DotFiles Config
  hosts: localhost
  connection: local
  vars_files:
    - "{{ lookup('env', 'HOME') }}/.config/dotfiles_env_vars"
    - "group_vars/all.yaml"

  pre_tasks:
    - name: Load and validate environment
      ansible.builtin.import_tasks: pre_tasks/load_dotfiles_env.yaml
      tags:
        - always

    - name: Detect Host User
      ansible.builtin.import_tasks: pre_tasks/whoami.yaml
      tags:
        - always

    - name: Detect 1Password
      ansible.builtin.import_tasks: pre_tasks/detect_1password.yaml
      tags:
        - always

  tasks:
    - name: Merge base and additional roles by category
      ansible.builtin.set_fact:
        merged_roles: >-
          {{
            base_roles | combine(additional_roles | default({}), recursive=true)
          }}
      tags:
        - always

    # Core category
    - name: Run core roles
      ansible.builtin.import_tasks: tasks/run_category_roles.yaml
      vars:
        category_name: core
      tags:
        - core

    # Shell category
    - name: Run shell roles
      ansible.builtin.import_tasks: tasks/run_category_roles.yaml
      vars:
        category_name: shell
      tags:
        - shell

    # CLI category
    - name: Run cli roles
      ansible.builtin.import_tasks: tasks/run_category_roles.yaml
      vars:
        category_name: cli
      tags:
        - cli

    # Dev category
    - name: Run dev roles
      ansible.builtin.import_tasks: tasks/run_category_roles.yaml
      vars:
        category_name: dev
      tags:
        - dev

    # DevOps category
    - name: Run devops roles
      ansible.builtin.import_tasks: tasks/run_category_roles.yaml
      vars:
        category_name: devops
      tags:
        - devops

    # Utils category
    - name: Run utils roles
      ansible.builtin.import_tasks: tasks/run_category_roles.yaml
      vars:
        category_name: utils
      tags:
        - utils

    # Apps category
    - name: Run apps roles
      ansible.builtin.import_tasks: tasks/run_category_roles.yaml
      vars:
        category_name: apps
      tags:
        - apps

    # Media category
    - name: Run media roles
      ansible.builtin.import_tasks: tasks/run_category_roles.yaml
      vars:
        category_name: media
      tags:
        - media

    # Gaming category
    - name: Run gaming roles
      ansible.builtin.import_tasks: tasks/run_category_roles.yaml
      vars:
        category_name: gaming
      tags:
        - gaming
