---
- name: DotFiles Config
  hosts: localhost
  connection: local
  vars_files:
    - "{{ lookup('env', 'HOME') }}/.config/dotfiles_env_vars"
    - "group_vars/all.yaml"

  pre_tasks:
    - name: Load and validate environment
      ansible.builtin.import_tasks: pre_tasks/load_dotfiles_env.yaml
      tags:
        - always

    - name: Detect Host User
      ansible.builtin.import_tasks: pre_tasks/whoami.yaml
      tags:
        - always

    - name: Detect 1Password
      ansible.builtin.import_tasks: pre_tasks/detect_1password.yaml
      tags:
        - always

  tasks:
    - name: Set pre roles
      ansible.builtin.set_fact:
        pre_run_roles: >-
          {{
            ('all' in ansible_run_tags) | ternary(
              pre_roles | difference(exclude_roles | default([])) | sort,
              ansible_run_tags | difference(exclude_roles | default([])) | sort
            )
          }}
      tags:
        - always

    - name: Set default roles
      ansible.builtin.set_fact:
        default_run_roles: >-
          {{
            ('all' in ansible_run_tags) | ternary(
              default_roles | difference(exclude_roles | default([])) | sort,
              ansible_run_tags | difference(exclude_roles | default([])) | sort
            )
          }}
      tags:
        - always

    - name: Set additional environment-specific roles
      ansible.builtin.set_fact:
        additional_run_roles: >-
          {{
            ('all' in ansible_run_tags) | ternary(
              additional_roles | difference(exclude_roles | default([])) | sort,
              ansible_run_tags | difference(exclude_roles | default([])) | sort
            )
          }}
      tags:
        - always

    - name: Run pre roles
      ansible.builtin.include_role:
        apply:
          tags:
            - "{{ roles_item }}"
        name: "{{ roles_item }}"
      loop_control:
        loop_var: roles_item
      with_items: "{{ pre_run_roles }}"
      tags:
        - always

    - name: Run default roles
      ansible.builtin.include_role:
        apply:
          tags:
            - "{{ roles_item }}"
        name: "{{ roles_item }}"
      loop_control:
        loop_var: roles_item
      with_items: "{{ default_run_roles }}"
      tags:
        - always

    - name: Run environment-specific roles
      ansible.builtin.include_role:
        apply:
          tags:
            - "{{ roles_item }}"
        name: "{{ roles_item }}"
      loop_control:
        loop_var: roles_item
      with_items: "{{ additional_run_roles }}"
      tags:
        - always
      when: additional_run_roles
