---
- name: DotFiles Config
  hosts: localhost
  connection: local
  vars_files:
    - "{{ lookup('env', 'HOME') }}/.config/dotfiles_env_vars"
    - "group_vars/all.yaml"

  pre_tasks:
    - name: Load and validate environment
      ansible.builtin.import_tasks: pre_tasks/load_dotfiles_env.yaml
      tags:
        - always

    - name: Detect Host User
      ansible.builtin.import_tasks: pre_tasks/whoami.yaml
      tags:
        - always

    - name: Detect 1Password
      ansible.builtin.import_tasks: pre_tasks/detect_1password.yaml
      tags:
        - always

  tasks:
    - name: Set roles
      ansible.builtin.set_fact:
        run_roles: "{{ ansible_run_tags != ['all'] and ansible_run_tags or default_roles | difference(exclude_roles | default([])) | sort }}"
      tags:
        - always

    - name: Run roles
      ansible.builtin.include_role:
        apply:
          tags:
            - "{{ roles_item }}"
        name: "{{ roles_item }}"
      loop_control:
        loop_var: roles_item
      with_items: "{{ run_roles }}"
      tags:
        - always
