---
- name: "{{ role_name }} | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yaml"
  register: distribution_config

- name: "{{ role_name }} | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yaml"
  when: distribution_config.stat.exists

- name: K8s | Ensure .kube directory exists
  ansible.builtin.file:
    path: "~/.kube"
    state: directory
    mode: "0755"

- name: K8s | Create .kube/config file from 1Password
  ansible.builtin.copy:
    content: "{{ op_lookup[k8s.kubeconfig.opLookupId] }}"
    dest: "~/.kube/config"
    mode: "0600"
  when: k8s.kubeconfig.opLookupId is defined and op_lookup[k8s.kubeconfig.opLookupId] is defined
