---
- name: K8s | Adding kubernetes apt key
  ansible.builtin.apt_key:
    url: "https://pkgs.k8s.io/core:/stable:/{{ k8s.repo.version }}/deb/Release.key"
    state: present
    keyring: "/etc/apt/keyrings/kubernetes-apt-keyring.gpg"
  become: true

- name: K8s | Adding kubernetes apt repo
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/{{ k8s.repo.version }}/deb/ /"
    filename: pkgs.k8s.io_core_stable_deb
    mode: "0644"
  become: true

- name: K8s | Installing Kubernetes
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    force: true
  loop:
    - kubectl
  become: true
