---
- name: "K8s | MacOSX | Install kubernetes tools"
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop:
    - kubernetes-cli
    - kubectl-cnpg
    - kubectx
    - kubelogin

