---
- name: "{{ role_name }} | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yaml"
  register: distribution_config

- name: "{{ role_name }} | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yaml"
  when: distribution_config.stat.exists

- name: "{{ role_name }} | Ensure config directories exist"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/omp"
    state: directory
    mode: "0755"

- name: "{{ role_name }} | Copy custom oh-my-posh configs"
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/omp/{{ item | basename }}"
    src: "{{ item }}"
    mode: "0644"
  with_fileglob:
    - "{{ role_path }}/files/*"
