---
- name: "{{ role_name }} | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yaml"
  register: distribution_config

- name: "{{ role_name }} | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yaml"
  when: distribution_config.stat.exists

# - name: "System | Set hosts"
#   ansible.builtin.template:
#     dest: "/etc/hosts"
#     src: hosts.j2
#     mode: "0644"
#   become: true
#   when: not ansible_host_environment_is_wsl

# # FIXME: Follow the SSH vault.yaml structure of looping over op keys
# # and adding them to etc-hosts after the above template is laid down.
# - name: "System | Get Host from Vault"
#   ansible.builtin.command:
#     cmd: op --account my.1password.com read op://Raft/rdp-demo-local-ingress/notesPlain
#   register: rdp_demo_local_ingress_hosts
#   changed_when: false

# # FIXME: This needs to more dynamically apply op host entries.
# # See above `fixme:` for more info
# - name: "System | Add Vault Hosts to /etc/hosts"
#   when: rdp_demo_local_ingress_hosts is defined
#   ansible.builtin.lineinfile:
#     line: "{{ rdp_demo_local_ingress_hosts.stdout }}"
#     path: /etc/hosts
#   become: true

# # FIXME: Follow the SSH vault.yaml structure of looping over op keys
# # and adding them to etc-hosts after the above template is laid down.
# - name: "System | Get updm-rdp-ingress Host from Vault"
#   ansible.builtin.command:
#     cmd: op --account my.1password.com read op://Raft/updm-rdp-ingress/notesPlain
#   register: updm_rdp_ingress_hosts
#   changed_when: false

# # FIXME: This needs to more dynamically apply op host entries.
# # See above `fixme:` for more info
# - name: "System | Add updm-rdp-ingress Vault Hosts to /etc/hosts"
#   when: updm_rdp_ingress_hosts is defined
#   ansible.builtin.lineinfile:
#     line: "{{ updm_rdp_ingress_hosts.stdout }}"
#     path: /etc/hosts
#   become: true
