---
- name: "SSH | Deploy SSH keys from Vault"
  when: op_installed
  ansible.builtin.include_tasks: ssh_keys.yaml
  with_items: "{{ op.ssh.github.techdufus }}"

# - name: Copy config
#   ansible.builtin.template:
#     dest: "{{ ansible_user_dir }}/.ssh/config"
#     src: "config.j2"
