---
- name: "System | MacOSX | Update Homebrew"
  community.general.homebrew:
    update_homebrew: true
    upgrade_all: true

- name: "System | MacOSX | Install Homebrew Packages"
  community.general.homebrew:
    name: "jq"
    state: present

- name: "System | MacOSX | Enable Passwordless Sudo"
  ansible.builtin.template:
    src: user-sudo.j2
    dest: /private/etc/sudoers.d/{{ ansible_env['USER'] }}
    mode: "0440"
  become: true
