---
- name: "Zsh | MacOSX | Install"
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop:
    - zsh

- name: "Zsh | Set default terminal"
  ansible.builtin.user:
    name: "{{ host_user }}"
    shell: /opt/homebrew/bin/zsh
  become: true
