---
- name: "{{ role_name }} | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yaml"
  register: distribution_config

- name: "{{ role_name }} | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yaml"
  when: distribution_config.stat.exists

- name: "Kitty | MacOSX | Deploy Kitty Config"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/kitty"
    mode: "0755"
    state: directory

- name: "Kitty | MacOSX | Deploy Kitty Config: {{ kitty_config }}"
  ansible.builtin.copy:
    src: "kitty.conf"
    dest: "{{ ansible_user_dir }}/.config/kitty/kitty.conf"
    mode: "0644"
