---
- name: "{{ role_name }} | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yaml"
  register: distribution_config

- name: "{{ role_name }} | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yaml"
  when: distribution_config.stat.exists

# Configure user settings from group_vars using op_lookup
- name: "Git | Set user.name from op_lookup"
  when: git.user.default.name.opLookupId is defined and op_lookup[git.user.default.name.opLookupId] is defined
  ansible.builtin.set_fact:
    git: "{{ git | combine({'user': {'default': {'name': op_lookup[git.user.default.name.opLookupId]}}}, recursive=True) }}"
  no_log: true

- name: "Git | Set user.email from op_lookup"
  when: git.user.default.email.opLookupId is defined and op_lookup[git.user.default.email.opLookupId] is defined
  ansible.builtin.set_fact:
    git: "{{ git | combine({'user': {'default': {'email': op_lookup[git.user.default.email.opLookupId]}}}, recursive=True) }}"
  no_log: true

- name: "Git | Set user.signingkey from op_lookup"
  when: git.user.default.signingkey.opLookupId is defined and op_lookup[git.user.default.signingkey.opLookupId] is defined
  ansible.builtin.set_fact:
    git: "{{ git | combine({'user': {'default': {'signingkey': op_lookup[git.user.default.signingkey.opLookupId]}}}, recursive=True) }}"
  no_log: true

# Process additional git users if they exist
- name: "Git | Process additional users from op_lookup"
  when: git.user.additional is defined
  block:
    - name: "Git | Process additional users from op_lookup"
      include_tasks: process_additional_user.yaml
      loop: "{{ git.user.additional | default([]) }}"
      loop_control:
        loop_var: additional_user
        index_var: user_index

# Create main gitconfig file from template
- name: "Git | Create .gitconfig file"
  ansible.builtin.template:
    src: "git-config.j2"
    dest: "{{ ansible_user_dir }}/.gitconfig"
    mode: '0644'
