---
# Process a single additional user's 1Password references using op_lookup
- name: "Git | Process all op_lookup for additional user at once"
  ansible.builtin.set_fact:
    processed_user: "{{ additional_user }}"

- name: "Git | Set additional user email from op_lookup"
  when: additional_user.email.opLookupId is defined and op_lookup[additional_user.email.opLookupId] is defined
  ansible.builtin.set_fact:
    processed_user: "{{ processed_user | combine({'email': op_lookup[additional_user.email.opLookupId]}) }}"
  no_log: true

- name: "Git | Set additional user signingkey from op_lookup"
  when: additional_user.signingkey.opLookupId is defined and op_lookup[additional_user.signingkey.opLookupId] is defined
  ansible.builtin.set_fact:
    processed_user: "{{ processed_user | combine({'signingkey': op_lookup[additional_user.signingkey.opLookupId]}) }}"
  no_log: true

- name: "Git | Set additional user name from op_lookup"
  when: additional_user.name.opLookupId is defined and op_lookup[additional_user.name.opLookupId] is defined
  ansible.builtin.set_fact:
    processed_user: "{{ processed_user | combine({'name': op_lookup[additional_user.name.opLookupId]}) }}"
  no_log: true

# Ensure gitdir exists with proper handling of tilde (~)
- name: "Git | Ensure gitdir exists"
  ansible.builtin.file:
    path: "{{ processed_user.gitdir | expanduser }}"
    state: directory
    mode: '0755'
  when: processed_user.gitdir is defined

# Create conditional gitconfig file for this additional user
- name: "Git | Create conditional gitconfig file"
  ansible.builtin.template:
    src: "git-config-conditional.j2"
    dest: "{{ ansible_user_dir }}/.gitconfig-{{ processed_user.id }}"
    mode: '0644'
  when: processed_user.name is defined and processed_user.name != '' and 
        processed_user.email is defined and processed_user.email != '' and 
        processed_user.gitdir is defined and processed_user.gitdir != '' and 
        processed_user.id is defined and processed_user.id != ''
