---
- name: "{{ role_name }} | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yaml"
  register: distribution_config

- name: "{{ role_name }} | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yaml"
  when: distribution_config.stat.exists

- name: "Vim | Copy .vimrc configuration"
  ansible.builtin.copy:
    src: .vimrc
    dest: "{{ ansible_user_dir }}/.vimrc"
    mode: '0644'
