---
- name: "{{ role_name }} | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yaml"
  register: distribution_config

- name: "{{ role_name }} | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yaml"
  when: distribution_config.stat.exists

- name: Install gcloud components
  ansible.builtin.command: "{{ ansible_env.HOME }}/.google-cloud-sdk/bin/gcloud components install {{ item }} --quiet"
  with_items: "{{ gcloud.components | default([]) }}"
  register: gcloud_component_install
  changed_when: "'is already installed' not in gcloud_component_install.stdout"

- name: Add gcloud update command to update config
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.config/update-commands.conf"
    line: "gcloud components update --quiet;Google Cloud SDK"
    state: present
    create: false