---
- name: "Tmux | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yaml"
  register: tmux_distribution_config

- name: "Tmux | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yaml"
  when: tmux_distribution_config.stat.exists

- name: "Tmux | Install TPM"
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm

- name: "Tmux | Configure tmux"
  ansible.builtin.copy:
    src: tmux
    dest: "{{ ansible_user_dir }}/.config/"
    mode: "0644"
    directory_mode: "0755"
    force: true

- name: "Tmux | Ensure .ssh directory exists"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.ssh"
    state: directory
    mode: "0700"

- name: "Tmux | Copy ssh_agent_fix to .ssh/rc"
  ansible.builtin.copy:
    src: tmux/ssh_agent_fix
    dest: "{{ ansible_user_dir }}/.ssh/rc"
    mode: "0644"
    force: true
