$schema: https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json
blocks:
  - alignment: left
    leading_diamond: <#7eb8da>┏</>
    segments:
      - foreground: '#7eb8da'
        style: plain
        template: '[<#ffffff></> {{ .UserName }} :: <#ffffff></> {{ .HostName }}]'
        type: session
      - foreground: '#f36943'
        foreground_templates:
          - '{{if eq "Charging" .State.String}}#40c4ff{{end}}'
          - '{{if eq "Discharging" .State.String}}#ff5722{{end}}'
          - '{{if eq "Full" .State.String}}#4caf50{{end}}'
        properties:
          charged_icon: '<#ffffff></> '
          charging_icon: ' '
          discharging_icon: '<#ffff00></> '
        style: plain
        template: '[{{ if not .Error }}{{ .Icon }}{{ .Percentage }}{{ end }}{{ .Error }}]'
        type: battery
    type: prompt
  - alignment: right
    segments:
      - foreground: '#be9ddf'
        properties:
          style: dallas
          threshold: 0
        style: diamond
        template: '[<#ffffff></> {{ .FormattedMs }}s]'
        type: executiontime
      - foreground: '#ffa5d8'
        style: diamond
        template: "[<#ffffff>\uf10fe</> <#ffff00>{{.Context}}</>{{if .Namespace}} :: <#ffff00>{{.Namespace}}</>{{end}}]"
        type: kubectl
    type: prompt
  - alignment: left
    newline: true
    leading_diamond: <#7eb8da>┣</>
    segments:
      - foreground: '#7eb8da'
        properties:
          style: full
        style: diamond
        template: '[<#ffffff></> <#98bfad>{{ .Path }}</>]'
        type: path
    type: prompt
  - alignment: right
    segments:
      - foreground: '#ffa5d8'
        properties:
          fetch_stash_count: true
          fetch_status: true
          fetch_upstream_icon: true
        style: plain
        template: '[<#ffffff>{{ .UpstreamIcon }} </>{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }} <#ffffff></> {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }} <#ffffff></> {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }} <#ffffff></> {{ .StashCount }}{{ end }}]'
        type: git
    type: prompt
  - alignment: left
    newline: true
    leading_diamond: <#7eb8da>└─</>
    segments:
      - style: diamond
        template: <#ffff00>[#]</>
        type: root
      - foreground: '#ffa5d8'
        style: diamond
        template: '<red></>'
        type: status
      - style: diamond
        template: '>'
        type: text
    type: prompt
final_space: true
secondary_prompt:
  background: transparent
  template: ' '
valid_line:
  background: transparent
  template: '> '
error_line:
  background: transparent
  template: '<#ff0000></> '
version: 3
