# Iterate over the 'op' list from group_vars and read secrets from 1Password
- name: Read secrets from 1Password
  vars:
    op_lookup: {}
  no_log: true
  block:
    - name: Read secret for each op entry
      changed_when: false
      ansible.builtin.command: >
        op read --account="{{ item.account }}" "{{ item.uri }}"
      loop: "{{ op }}"
      loop_control:
        label: "{{ item.id }}"
      register: op_read_results

    - name: Build op_lookup dictionary
      changed_when: false
      set_fact:
        op_lookup: "{{ op_lookup | combine({ item.item.id: item.stdout }) }}"
      loop: "{{ op_read_results.results }}"
      loop_control:
        label: "{{ item.item.id }}"
