---
- name: Fail if environment is not defined
  ansible.builtin.fail:
    msg: "Environment not specified. Please run with --env=work or --env=personal to set your environment"
  when: dotfiles_env is not defined or dotfiles_env == ""
  tags:
    - always

- name: Check if environment file exists
  ansible.builtin.stat:
    path: "{{ playbook_dir }}/group_vars/{{ dotfiles_env }}.yaml"
  register: env_file
  tags:
    - always

- name: Fail if environment file doesn't exist
  ansible.builtin.fail:
    msg: "Environment file for '{{ dotfiles_env }}' not found at {{ playbook_dir }}/group_vars/{{ dotfiles_env }}.yaml"
  when: dotfiles_env is defined and not env_file.stat.exists
  tags:
    - always

- name: Include environment-specific vars file
  ansible.builtin.include_vars:
    file: "group_vars/{{ dotfiles_env }}.yaml"
  when: dotfiles_env is defined and env_file.stat.exists
  tags:
    - always

- name: Debug environment
  ansible.builtin.debug:
    msg: "Using environment: {{ dotfiles_env | default('none') }}"
  tags:
    - always
