name: Ansible CI
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install ansible-lint
        run: pip install ansible-lint
      - name: Install Galaxy Modules
        run: ansible-galaxy install -r requirements/common.yaml
      - name: Linting set_env playbook with ansible-lint
        run: ansible-lint set_env.yaml
      - name: Linting main playbook with ansible-lint
        run: ansible-lint main.yaml
