---
- name: "Bat | MacOSX | Install bat"
  community.general.homebrew:
    name: bat
    state: present

# wget -P "$(bat --config-dir)/themes" https://github.com/catppuccin/bat/raw/main/themes/Catppuccin%20Mocha.tmTheme

- name: "Bat | MacOSX | Create bat themes directory"
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.config/bat/themes"
    state: directory
    mode: "0755"

- name: "Bat | MacOSX | Install bat config"
  ansible.builtin.copy:
    src: config
    dest: "{{ lookup('env', 'HOME') }}/.config/bat/config"
    mode: "0644"

- name: "Bat | MacOSX | Install bat themes"
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/catppuccin/bat/main/themes/Catppuccin%20Mocha.tmTheme"
    dest: "{{ lookup('env', 'HOME') }}/.config/bat/themes/Catppuccino Mocha.tmTheme"
    mode: "0644"
